/** @typedef {{id:string,label:string,icon:string,color:string,group:string}} CatalogItem */

/** Curated components with original SVG pictograms and provider accents. @type {CatalogItem[]} */
export const catalog = [
  ["aws-ec2", "EC2", "server", "#ff9900", "AWS"],
  ["aws-s3", "S3", "bucket", "#ff9900", "AWS"],
  ["aws-lambda", "Lambda", "function", "#ff9900", "AWS"],
  ["aws-rds", "RDS", "database", "#ff9900", "AWS"],
  ["aws-vpc", "VPC", "network", "#ff9900", "AWS"],
  ["azure-vm", "Virtual Machines", "server", "#35a6ef", "Azure"],
  ["azure-storage", "Blob Storage", "storage", "#35a6ef", "Azure"],
  ["azure-functions", "Functions", "function", "#35a6ef", "Azure"],
  ["azure-sql", "Azure SQL", "database", "#35a6ef", "Azure"],
  ["gcp-compute", "Compute Engine", "server", "#4285f4", "GCP"],
  ["gcp-storage", "Cloud Storage", "storage", "#4285f4", "GCP"],
  ["gcp-functions", "Cloud Functions", "function", "#4285f4", "GCP"],
  ["gcp-bigquery", "BigQuery", "analytics", "#4285f4", "GCP"],
  ["github", "GitHub", "git", "#e7e7e7", "DevOps"],
  ["gitlab", "GitLab", "git", "#fc6d26", "DevOps"],
  ["kubernetes", "Kubernetes", "cluster", "#326ce5", "DevOps"],
  ["docker", "Docker", "container", "#2496ed", "DevOps"],
  ["terraform", "Terraform", "blocks", "#844fba", "DevOps"],
  ["argocd", "ArgoCD", "deploy", "#ef7b4d", "DevOps"],
  ["jenkins", "Jenkins", "workflow", "#d24939", "DevOps"],
  ["port", "Port", "portal", "#a6eb5f", "DevOps"],
  ["backstage", "Backstage", "portal", "#9bf0ef", "DevOps"],
  ["n8n", "n8n", "workflow", "#ea4b71", "DevOps"],
  ["kafka", "Kafka", "stream", "#f2f2f2", "Data & Messaging"],
  ["redis", "Redis", "cache", "#dc382d", "Data & Messaging"],
  ["postgresql", "PostgreSQL", "database", "#6b9ac4", "Data & Messaging"],
  ["mongodb", "MongoDB", "documentDb", "#47a248", "Data & Messaging"],
  ["rabbitmq", "RabbitMQ", "queue", "#ff6600", "Data & Messaging"],
  ["grafana", "Grafana", "chart", "#f46800", "Observability"],
  ["prometheus", "Prometheus", "flame", "#e6522c", "Observability"],
  ["loki", "Loki", "logs", "#a6d66e", "Observability"],
  ["tempo", "Tempo", "traces", "#f9c866", "Observability"],
  ["opentelemetry", "OpenTelemetry", "telemetry", "#7195e4", "Observability"],
].map(([id, label, icon, color, group]) => ({ id, label, icon, color, group }));

export const catalogById = new Map(catalog.map((item) => [item.id, item]));
