/** @typedef {{id:string,label:string,glyph:string,color:string,group:string}} CatalogItem */
/** Curated provider and platform primitives. Symbols are intentionally local and offline. @type {CatalogItem[]} */
export const catalog = [
  ["aws-ec2", "EC2", "EC", "#ff9900", "AWS"],
  ["aws-s3", "S3", "S3", "#ff9900", "AWS"],
  ["aws-lambda", "Lambda", "λ", "#ff9900", "AWS"],
  ["aws-rds", "RDS", "DB", "#ff9900", "AWS"],
  ["aws-vpc", "VPC", "◇", "#ff9900", "AWS"],
  ["azure-vm", "Virtual Machines", "VM", "#35a6ef", "Azure"],
  ["azure-storage", "Blob Storage", "◫", "#35a6ef", "Azure"],
  ["azure-functions", "Functions", "ƒ", "#35a6ef", "Azure"],
  ["azure-sql", "Azure SQL", "DB", "#35a6ef", "Azure"],
  ["gcp-compute", "Compute Engine", "CE", "#4285f4", "GCP"],
  ["gcp-storage", "Cloud Storage", "◫", "#4285f4", "GCP"],
  ["gcp-functions", "Cloud Functions", "ƒ", "#4285f4", "GCP"],
  ["gcp-bigquery", "BigQuery", "BQ", "#4285f4", "GCP"],
  ["github", "GitHub", "GH", "#e7e7e7", "DevOps"],
  ["gitlab", "GitLab", "GL", "#fc6d26", "DevOps"],
  ["kubernetes", "Kubernetes", "K8", "#326ce5", "DevOps"],
  ["docker", "Docker", "DK", "#2496ed", "DevOps"],
  ["terraform", "Terraform", "TF", "#844fba", "DevOps"],
  ["argocd", "ArgoCD", "Ar", "#ef7b4d", "DevOps"],
  ["jenkins", "Jenkins", "Jn", "#d24939", "DevOps"],
  ["port", "Port", "Pt", "#a6eb5f", "DevOps"],
  ["backstage", "Backstage", "Bs", "#9bf0ef", "DevOps"],
  ["n8n", "n8n", "n8", "#ea4b71", "DevOps"],
  ["kafka", "Kafka", "Kf", "#f2f2f2", "Data & Messaging"],
  ["redis", "Redis", "Rd", "#dc382d", "Data & Messaging"],
  ["postgresql", "PostgreSQL", "Pg", "#6b9ac4", "Data & Messaging"],
  ["mongodb", "MongoDB", "Mg", "#47a248", "Data & Messaging"],
  ["rabbitmq", "RabbitMQ", "Rq", "#ff6600", "Data & Messaging"],
  ["grafana", "Grafana", "Gf", "#f46800", "Observability"],
  ["prometheus", "Prometheus", "Pm", "#e6522c", "Observability"],
  ["loki", "Loki", "Lk", "#a6d66e", "Observability"],
  ["tempo", "Tempo", "Tp", "#f9c866", "Observability"],
  ["opentelemetry", "OpenTelemetry", "OT", "#7195e4", "Observability"],
].map(([id, label, glyph, color, group]) => ({
  id,
  label,
  glyph,
  color,
  group,
}));
export const catalogById = new Map(catalog.map((item) => [item.id, item]));
